### ISSUE TITLE
getting tests to work

### ISSUE THREAD

**Issue by rocketNeck** [learn-co-curriculum/react-changing-state-lab#12]
i ran $learn 
I got a nomethod error...

I had to install: 

`    "react-test-renderer": "^15.5.4",
    "react-dom": "^15.3.0",`

... in package.json in order to get tests to run for this lab. 

There seems to have been a breaking change to react-addons-test-utils

**Comment by sgharms** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
