### ISSUE TITLE
npm test no run the test.

### ISSUE THREAD

**Issue by CharlyJazz** [learn-co-curriculum/react-changing-state-lab#14]

**Comment by sgharms** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
