### ISSUE TITLE
Issues still not fixed 1 year later

### ISSUE THREAD

**Issue by mjhough** [learn-co-curriculum/react-changing-state-lab#15]
How can these issues still be present a year later?

I'm leaving this here so it will hopefully get someones attention.

**Comment by sgharms** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
