### ISSUE TITLE
Requires dependency installs

### ISSUE THREAD

**Issue by Traci7822** [learn-co-curriculum/react-changing-state-lab#7]
'Learn' tests ran find at first but about half way through the lab I had to install tons of npm dependencies to continue testing....

npm install mocha
npm install mocha-multi
npm install babel-register
npm install --save-dev babel-cli babel-preset-es2015
npm install --save-dev babel-cli babel-preset-react
npm install jsdom
npm install expect
npm install react
npm install react-dom
npm install enzyme
npm install react-addons-test-utils
npm install sinon

**Comment by Traci7822** [comment]
To run 'npm run bundle' I also had to install the following:

npm install browserify
npm install babelify

**Comment by sgharms** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
